require("DynamoDan.remap")
require("DynamoDan.set")
require("DynamoDan.intelephense")
require("DynamoDan.packer")
require("DynamoDan.opts")
require("DynamoDan.rust-completion")
print("Howdy do, DynamoDan!")
